// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdkPIk-koDS49b2uelCrOHBe1b_BgMnw',
    appId: '1:54186993513:web:fcd806d750ef07d4563ff8',
    messagingSenderId: '54186993513',
    projectId: 'alu-launch-305a4',
    authDomain: 'alu-launch-305a4.firebaseapp.com',
    storageBucket: 'alu-launch-305a4.firebasestorage.app',
    measurementId: 'G-FCEVMWQEVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-gpfQWk3sgO2irPB1aE8c6D6y0ii3lo',
    appId: '1:54186993513:android:f734730b5aae300a563ff8',
    messagingSenderId: '54186993513',
    projectId: 'alu-launch-305a4',
    storageBucket: 'alu-launch-305a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKMTt37HNWuhFL4LHxadm4f6gNY1mxwQI',
    appId: '1:54186993513:ios:40fff65ef66b756c563ff8',
    messagingSenderId: '54186993513',
    projectId: 'alu-launch-305a4',
    storageBucket: 'alu-launch-305a4.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKMTt37HNWuhFL4LHxadm4f6gNY1mxwQI',
    appId: '1:54186993513:ios:40fff65ef66b756c563ff8',
    messagingSenderId: '54186993513',
    projectId: 'alu-launch-305a4',
    storageBucket: 'alu-launch-305a4.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZdkPIk-koDS49b2uelCrOHBe1b_BgMnw',
    appId: '1:54186993513:web:9f6e66ff6c222de3563ff8',
    messagingSenderId: '54186993513',
    projectId: 'alu-launch-305a4',
    authDomain: 'alu-launch-305a4.firebaseapp.com',
    storageBucket: 'alu-launch-305a4.firebasestorage.app',
    measurementId: 'G-PXRRSB8RJC',
  );
}
